// <auto-generated />
using System;
using InventoryX_Transactional.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryX_Transactional.Data.Migrations
{
    [DbContext(typeof(InventoryXDbContext))]
    [Migration("20231022223403_DataForClientAndProvider")]
    partial class DataForClientAndProvider
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryX_Transactional.Data.Models.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9358));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLegal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ClientId");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = new Guid("d74a7786-f6f4-4076-a971-83078352f532"),
                            Address = "123 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6676),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "12345678",
                            DocumentType = 1,
                            Email = "alice@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Alice Chains",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            ClientId = new Guid("d65466d1-d593-4e26-b041-35d40fd6b6f7"),
                            Address = "456 Elm St, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6685),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "21345678901",
                            DocumentType = 2,
                            Email = "bob@yahoo.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Pepitos S.A.C",
                            Phone = "555-234-5678"
                        },
                        new
                        {
                            ClientId = new Guid("62c074b9-53cc-41bf-a33a-1cfa77d8923f"),
                            Address = "789 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6691),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "87654321",
                            DocumentType = 1,
                            Email = "charlie@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Charlie Martinez",
                            Phone = "555-345-6789"
                        },
                        new
                        {
                            ClientId = new Guid("0291ac52-7d67-415d-95c3-f13d5e1bde18"),
                            Address = "567 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6694),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "007654321098765",
                            DocumentType = 3,
                            Email = "david@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "David Aguilar",
                            Phone = "555-456-7890"
                        },
                        new
                        {
                            ClientId = new Guid("6e34f5b4-0943-4a1c-99cf-9a4a0161e1af"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6697),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "13456789012",
                            DocumentType = 2,
                            Email = "eve@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Eve Medina",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("1e07d6b2-b64d-4a3f-935a-2f01c655000b"),
                            Address = "321 Oak Dr, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6701),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "54321678",
                            DocumentType = 1,
                            Email = "frank@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Frank Jones",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("307f0a84-3b9d-4b56-956c-895f35329e86"),
                            Address = "789 Elm St, Chicago",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6704),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "002356789012345",
                            DocumentType = 3,
                            Email = "grace@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Grace",
                            Phone = "555-111-2222"
                        },
                        new
                        {
                            ClientId = new Guid("995672a8-2064-41d0-856c-6bfae366c078"),
                            Address = "456 Maple Ave, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6723),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "24567890123",
                            DocumentType = 2,
                            Email = "holly@yahoo.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Holly Store S.A.",
                            Phone = "555-444-5555"
                        },
                        new
                        {
                            ClientId = new Guid("ce2d6792-aa82-4fe6-a83f-8bfdbecb2877"),
                            Address = "123 Cedar Ln, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6726),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "76543210",
                            DocumentType = 1,
                            Email = "ivy@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Ivy Williams",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("a8020912-dbed-4ff6-b730-f779008d927b"),
                            Address = "456 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6762),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "00345678601234",
                            DocumentType = 3,
                            Email = "jack@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Jack Smith",
                            Phone = "555-333-4444"
                        },
                        new
                        {
                            ClientId = new Guid("8e2d8daa-606e-45c2-98f3-f7fef8e23494"),
                            Address = "123 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6765),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "87654321",
                            DocumentType = 1,
                            Email = "karen@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Karen Riques",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("40e8ff14-fccf-4929-a979-522c04ffcce5"),
                            Address = "456 Elm St, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6768),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "004567890123458",
                            DocumentType = 3,
                            Email = "liam@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Liam Nesson",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            ClientId = new Guid("dfdd52a6-e221-4ece-9f80-249502840f75"),
                            Address = "789 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6771),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "22345228901",
                            DocumentType = 2,
                            Email = "mia@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Mia Shop",
                            Phone = "555-234-5678"
                        },
                        new
                        {
                            ClientId = new Guid("d01efb5b-8fdf-41c7-8ea5-3bad50388169"),
                            Address = "567 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6774),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "98765432",
                            DocumentType = 1,
                            Email = "noah@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Noah Azora",
                            Phone = "555-345-6789"
                        },
                        new
                        {
                            ClientId = new Guid("d4b75d97-1403-4a32-8fc4-148893a01858"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6777),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "007654321098765",
                            DocumentType = 3,
                            Email = "olivia@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Olivia Fernandez",
                            Phone = "555-456-7890"
                        },
                        new
                        {
                            ClientId = new Guid("53e869f0-a6d3-40a3-a9b7-9d04186d2b94"),
                            Address = "123 Maple Ave, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6784),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "23456789012",
                            DocumentType = 2,
                            Email = "parker@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Parker Corp.",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("c0278887-92ec-4f2a-ba81-65b99e28cd0b"),
                            Address = "321 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6786),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "54321678",
                            DocumentType = 1,
                            Email = "quinn@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Client Eastwood",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("b2229052-b97f-4baa-bcdf-3e38b693b486"),
                            Address = "789 Elm St, Chicago",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6790),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "001236789012345",
                            DocumentType = 3,
                            Email = "ryan@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Ryan Dominguez",
                            Phone = "555-111-2222"
                        },
                        new
                        {
                            ClientId = new Guid("b91c074e-e98b-4ded-9d7c-6cbe38170d7a"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6793),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "24567890697",
                            DocumentType = 2,
                            Email = "sofia@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Sofia Bazar",
                            Phone = "555-444-5555"
                        },
                        new
                        {
                            ClientId = new Guid("2a5475ee-8f8c-41cd-9811-42bceb31fa32"),
                            Address = "123 Oak Dr, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(6796),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "76543210",
                            DocumentType = 1,
                            Email = "thomas@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Thomas Philipp",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("ee603878-f0e6-4c00-a39a-e206349de6e3"),
                            Address = "123 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9569),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "12345678",
                            DocumentType = 1,
                            Email = "alice@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Alice Chains",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            ClientId = new Guid("24e9c1e9-76d5-46d7-8982-a5dddd20b9b5"),
                            Address = "456 Elm St, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9574),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "21345678901",
                            DocumentType = 2,
                            Email = "bob@yahoo.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Pepitos S.A.C",
                            Phone = "555-234-5678"
                        },
                        new
                        {
                            ClientId = new Guid("816e040b-a42e-4001-b4d4-4151e1c37265"),
                            Address = "789 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9577),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "87654321",
                            DocumentType = 1,
                            Email = "charlie@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Charlie Martinez",
                            Phone = "555-345-6789"
                        },
                        new
                        {
                            ClientId = new Guid("8d8b3dd5-3061-4f1f-8b85-cd4ae8d33b81"),
                            Address = "567 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9580),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "007654321098765",
                            DocumentType = 3,
                            Email = "david@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "David Aguilar",
                            Phone = "555-456-7890"
                        },
                        new
                        {
                            ClientId = new Guid("0fde0983-a635-43e0-95dd-15fccf167262"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9583),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "13456789012",
                            DocumentType = 2,
                            Email = "eve@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Eve Medina",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("ee7a5082-af4f-4586-b3bc-3137ed83c485"),
                            Address = "321 Oak Dr, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9588),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "54321678",
                            DocumentType = 1,
                            Email = "frank@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Frank Jones",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("329c5534-14d7-4ace-a7f7-8ce1c0faacf3"),
                            Address = "789 Elm St, Chicago",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9591),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "002356789012345",
                            DocumentType = 3,
                            Email = "grace@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Grace",
                            Phone = "555-111-2222"
                        },
                        new
                        {
                            ClientId = new Guid("216b1298-51e3-46b3-8e51-386b855a7659"),
                            Address = "456 Maple Ave, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9598),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "24567890123",
                            DocumentType = 2,
                            Email = "holly@yahoo.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Holly Store S.A.",
                            Phone = "555-444-5555"
                        },
                        new
                        {
                            ClientId = new Guid("0692a703-5670-4f9c-a986-56fa040a9126"),
                            Address = "123 Cedar Ln, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9601),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "76543210",
                            DocumentType = 1,
                            Email = "ivy@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Ivy Williams",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("df366bb1-4442-4da1-a6fa-09ba5fe4b691"),
                            Address = "456 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9605),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "00345678601234",
                            DocumentType = 3,
                            Email = "jack@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Jack Smith",
                            Phone = "555-333-4444"
                        },
                        new
                        {
                            ClientId = new Guid("0cbb2dc5-eeb6-4660-b15f-023b0fc1cb05"),
                            Address = "123 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9608),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "87654321",
                            DocumentType = 1,
                            Email = "karen@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Karen Riques",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("8570332f-c566-449c-a22f-f6f3d6786fcf"),
                            Address = "456 Elm St, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9610),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "004567890123458",
                            DocumentType = 3,
                            Email = "liam@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Liam Nesson",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            ClientId = new Guid("b03d3cb2-8b3c-42d0-a833-97cbe81d9705"),
                            Address = "789 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9613),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "22345228901",
                            DocumentType = 2,
                            Email = "mia@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Mia Shop",
                            Phone = "555-234-5678"
                        },
                        new
                        {
                            ClientId = new Guid("a7dff85e-a35a-4de5-aa6c-706e0a0684da"),
                            Address = "567 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9616),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "98765432",
                            DocumentType = 1,
                            Email = "noah@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Noah Azora",
                            Phone = "555-345-6789"
                        },
                        new
                        {
                            ClientId = new Guid("54874129-ba8f-4b85-b313-029190422c20"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9618),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "007654321098765",
                            DocumentType = 3,
                            Email = "olivia@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Olivia Fernandez",
                            Phone = "555-456-7890"
                        },
                        new
                        {
                            ClientId = new Guid("df1c9a6d-7935-47af-a2f0-9efb1cf7170d"),
                            Address = "123 Maple Ave, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9623),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "23456789012",
                            DocumentType = 2,
                            Email = "parker@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Parker Corp.",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("92103553-799a-4385-99ea-8aab44e9fc5c"),
                            Address = "321 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9626),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "54321678",
                            DocumentType = 1,
                            Email = "quinn@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Client Eastwood",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("f8c93620-042e-464c-86be-f05b56e7db1f"),
                            Address = "789 Elm St, Chicago",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9630),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "001236789012345",
                            DocumentType = 3,
                            Email = "ryan@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Ryan Dominguez",
                            Phone = "555-111-2222"
                        },
                        new
                        {
                            ClientId = new Guid("901d0afb-14d5-44df-ac87-c6c5f02acfbf"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9633),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "24567890697",
                            DocumentType = 2,
                            Email = "sofia@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Sofia Bazar",
                            Phone = "555-444-5555"
                        },
                        new
                        {
                            ClientId = new Guid("bb4ccddc-4706-4515-af0d-b856b5608847"),
                            Address = "123 Oak Dr, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(9636),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            DocumentNumber = "76543210",
                            DocumentType = 1,
                            Email = "thomas@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Thomas Philipp",
                            Phone = "555-987-6543"
                        });
                });

            modelBuilder.Entity("InventoryX_Transactional.Data.Models.Provider", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(269));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ProviderId");

                    b.ToTable("Provider", (string)null);

                    b.HasData(
                        new
                        {
                            ProviderId = new Guid("7dad4b4f-8fc3-4fab-9c61-c5f2f23fc2ed"),
                            Address = "P.O. Box 367, 4325 Augue Rd.",
                            BusinessName = "Augue Corporation",
                            ContactEmail = "in.tempus@google.com",
                            ContactPhone = "(498) 810-4710",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8172),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "28851161316"
                        },
                        new
                        {
                            ProviderId = new Guid("1b86e2bb-2b6b-49b9-bd2d-d32fe6960b8d"),
                            Address = "716-9139 Lectus, Road",
                            BusinessName = "Feugiat Nec Foundation",
                            ContactEmail = "ut.tincidunt@yahoo.net",
                            ContactPhone = "1-324-172-5394",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8178),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "21425812564"
                        },
                        new
                        {
                            ProviderId = new Guid("7ab86fca-0a1e-4d50-b721-54fa0a9d5cea"),
                            Address = "P.O. Box 994, 6300 Id Rd.",
                            BusinessName = "Dis Parturient Montes Associates",
                            ContactEmail = "donec.luctus@aol.edu",
                            ContactPhone = "1-948-625-3851",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8182),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "20907865658"
                        },
                        new
                        {
                            ProviderId = new Guid("b0a64515-d646-4be6-9e45-5a08007f0838"),
                            Address = "Ap #121-5878 Nulla. St.",
                            BusinessName = "Egestas Rhoncus Corp.",
                            ContactEmail = "pede@icloud.net",
                            ContactPhone = "(487) 387-0723",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8189),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "21438271486"
                        },
                        new
                        {
                            ProviderId = new Guid("3220758c-59e0-4b11-b6a7-2ccb757c13dd"),
                            Address = "523-8707 Et Rd.",
                            BusinessName = "Nullam Nisl Maecenas PC",
                            ContactEmail = "vulputate@protonmail.couk",
                            ContactPhone = "(685) 481-5523",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8192),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "23414517112"
                        },
                        new
                        {
                            ProviderId = new Guid("e4076494-29fb-4884-b475-b0a5b7a31a44"),
                            Address = "938-7069 Lobortis, Av.",
                            BusinessName = "Turpis Egestas Fusce Inc.",
                            ContactEmail = "donec.feugiat.metus@google.ca",
                            ContactPhone = "(744) 465-4414",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8196),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "20534218461"
                        },
                        new
                        {
                            ProviderId = new Guid("d56f024e-27f8-45df-b496-07b8d0e88832"),
                            Address = "Ap #717-2261 Mi Avenue",
                            BusinessName = "Sem Limited",
                            ContactEmail = "lacinia@yahoo.ca",
                            ContactPhone = "(512) 376-4277",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8199),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "27145868620"
                        },
                        new
                        {
                            ProviderId = new Guid("c1d0f324-0ab4-4fc4-a12b-b47d5ff4b75d"),
                            Address = "P.O. Box 145, 8931 Vitae Rd.",
                            BusinessName = "Elit A Feugiat Corp.",
                            ContactEmail = "consectetuer.ipsum.nunc@hotmail.net",
                            ContactPhone = "(445) 745-2317",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8202),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "28163725354"
                        },
                        new
                        {
                            ProviderId = new Guid("c9edfcde-e32d-4013-8610-b3054d84d111"),
                            Address = "Ap #312-3859 Arcu. Street",
                            BusinessName = "Vitae Velit LLC",
                            ContactEmail = "at@icloud.ca",
                            ContactPhone = "1-202-357-4151",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8204),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "20177426605"
                        },
                        new
                        {
                            ProviderId = new Guid("8858d818-9f0e-4f3d-b5d8-ba6c09332d6d"),
                            Address = "430-6187 Malesuada Ave",
                            BusinessName = "Lorem Ipsum Institute",
                            ContactEmail = "orci.donec.nibh@aol.ca",
                            ContactPhone = "(747) 407-6648",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8209),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "24334730132"
                        },
                        new
                        {
                            ProviderId = new Guid("7c504e79-0d6f-4a2c-8d95-e7146d077a4b"),
                            Address = "2259 Nunc St.",
                            BusinessName = "At Associates",
                            ContactEmail = "ac@icloud.ca",
                            ContactPhone = "1-335-797-0988",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8211),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "25016570928"
                        },
                        new
                        {
                            ProviderId = new Guid("21c74117-3b4f-47e6-9685-e17ffab7470f"),
                            Address = "318-3230 Urna. Rd.",
                            BusinessName = "Nibh Donec Est Institute",
                            ContactEmail = "proin.non.massa@aol.org",
                            ContactPhone = "1-854-225-3383",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8216),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "24821225133"
                        },
                        new
                        {
                            ProviderId = new Guid("a4cde0ff-0e29-4aae-9a6f-180da35dd705"),
                            Address = "Ap #645-3636 Conubia Av.",
                            BusinessName = "Erat Volutpat Inc.",
                            ContactEmail = "elit.pretium@icloud.com",
                            ContactPhone = "(681) 652-3427",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8219),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "21546823173"
                        },
                        new
                        {
                            ProviderId = new Guid("f75677d3-e332-41c3-987c-f4004821b368"),
                            Address = "163-409 In, Rd.",
                            BusinessName = "Proin Eget Institute",
                            ContactEmail = "lobortis.mauris@google.net",
                            ContactPhone = "1-640-831-2711",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8254),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "24419741745"
                        },
                        new
                        {
                            ProviderId = new Guid("b7bd3fb7-2c2b-4cb2-a794-9948a27432b2"),
                            Address = "Ap #398-2179 Ligula Rd.",
                            BusinessName = "Laoreet Posuere Ltd",
                            ContactEmail = "quis@yahoo.org",
                            ContactPhone = "1-331-293-1812",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8258),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "20381813145"
                        },
                        new
                        {
                            ProviderId = new Guid("00437607-dca0-458b-b618-5aa969abbe4d"),
                            Address = "573-5782 Ut Avenue",
                            BusinessName = "In Foundation",
                            ContactEmail = "fringilla.euismod.enim@outlook.couk",
                            ContactPhone = "(812) 908-3601",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8261),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "23374028741"
                        },
                        new
                        {
                            ProviderId = new Guid("cacedb40-c9a5-4fac-be38-49fa3be1277e"),
                            Address = "P.O. Box 398, 5701 Enim Ave",
                            BusinessName = "Suspendisse Tristique Neque Foundation",
                            ContactEmail = "sed@aol.com",
                            ContactPhone = "(548) 947-6178",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8264),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "23886134764"
                        },
                        new
                        {
                            ProviderId = new Guid("54eba86d-f2f3-4b93-9bc8-8e463337fe76"),
                            Address = "201 Auctor Rd.",
                            BusinessName = "Malesuada Associates",
                            ContactEmail = "ut.mi@icloud.com",
                            ContactPhone = "1-531-938-2251",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8268),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "28654072941"
                        },
                        new
                        {
                            ProviderId = new Guid("6d51b030-22c9-4d1a-9791-9ef2116c061d"),
                            Address = "733-4722 Mi. Avenue",
                            BusinessName = "Enim Sit Ltd",
                            ContactEmail = "ut.aliquam@icloud.com",
                            ContactPhone = "1-696-562-7023",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8271),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "28352851057"
                        },
                        new
                        {
                            ProviderId = new Guid("795cc4c5-c513-4962-be5c-6f7c25f93b18"),
                            Address = "P.O. Box 604, 2268 Ac St.",
                            BusinessName = "Massa Limited",
                            ContactEmail = "at.libero.morbi@google.couk",
                            ContactPhone = "1-628-221-7892",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 330, DateTimeKind.Local).AddTicks(8276),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "22184652687"
                        },
                        new
                        {
                            ProviderId = new Guid("4a7eb499-8102-4ac7-a056-7ac5ccb8e833"),
                            Address = "P.O. Box 367, 4325 Augue Rd.",
                            BusinessName = "Augue Corporation",
                            ContactEmail = "in.tempus@google.com",
                            ContactPhone = "(498) 810-4710",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(419),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "28851161316"
                        },
                        new
                        {
                            ProviderId = new Guid("3a03223f-6ee1-4eb5-9ec8-3279e96504b6"),
                            Address = "716-9139 Lectus, Road",
                            BusinessName = "Feugiat Nec Foundation",
                            ContactEmail = "ut.tincidunt@yahoo.net",
                            ContactPhone = "1-324-172-5394",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(456),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "21425812564"
                        },
                        new
                        {
                            ProviderId = new Guid("7c280667-5ef4-495f-be96-6e452d641375"),
                            Address = "P.O. Box 994, 6300 Id Rd.",
                            BusinessName = "Dis Parturient Montes Associates",
                            ContactEmail = "donec.luctus@aol.edu",
                            ContactPhone = "1-948-625-3851",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(459),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "20907865658"
                        },
                        new
                        {
                            ProviderId = new Guid("12468e86-2840-4f4c-af31-88a687a2c0f8"),
                            Address = "Ap #121-5878 Nulla. St.",
                            BusinessName = "Egestas Rhoncus Corp.",
                            ContactEmail = "pede@icloud.net",
                            ContactPhone = "(487) 387-0723",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(465),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "21438271486"
                        },
                        new
                        {
                            ProviderId = new Guid("736e1fbd-dc1a-4356-8495-dbaaac682822"),
                            Address = "523-8707 Et Rd.",
                            BusinessName = "Nullam Nisl Maecenas PC",
                            ContactEmail = "vulputate@protonmail.couk",
                            ContactPhone = "(685) 481-5523",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(468),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "23414517112"
                        },
                        new
                        {
                            ProviderId = new Guid("cb00e59b-ccbe-4107-9ee3-6a6d140d336b"),
                            Address = "938-7069 Lobortis, Av.",
                            BusinessName = "Turpis Egestas Fusce Inc.",
                            ContactEmail = "donec.feugiat.metus@google.ca",
                            ContactPhone = "(744) 465-4414",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(472),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "20534218461"
                        },
                        new
                        {
                            ProviderId = new Guid("8c4181da-be81-4d1b-a0d5-a68844851d5c"),
                            Address = "Ap #717-2261 Mi Avenue",
                            BusinessName = "Sem Limited",
                            ContactEmail = "lacinia@yahoo.ca",
                            ContactPhone = "(512) 376-4277",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(475),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "27145868620"
                        },
                        new
                        {
                            ProviderId = new Guid("13fe8d89-da49-49c5-8983-c6ceeef36f08"),
                            Address = "P.O. Box 145, 8931 Vitae Rd.",
                            BusinessName = "Elit A Feugiat Corp.",
                            ContactEmail = "consectetuer.ipsum.nunc@hotmail.net",
                            ContactPhone = "(445) 745-2317",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(478),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "28163725354"
                        },
                        new
                        {
                            ProviderId = new Guid("7a25bbba-3bf8-432c-8774-d00444616dad"),
                            Address = "Ap #312-3859 Arcu. Street",
                            BusinessName = "Vitae Velit LLC",
                            ContactEmail = "at@icloud.ca",
                            ContactPhone = "1-202-357-4151",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(480),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "20177426605"
                        },
                        new
                        {
                            ProviderId = new Guid("547f0486-2a83-4037-a766-a928d949473a"),
                            Address = "430-6187 Malesuada Ave",
                            BusinessName = "Lorem Ipsum Institute",
                            ContactEmail = "orci.donec.nibh@aol.ca",
                            ContactPhone = "(747) 407-6648",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(484),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "24334730132"
                        },
                        new
                        {
                            ProviderId = new Guid("74555b2d-ff80-485a-89bb-7ceadd13aa8b"),
                            Address = "2259 Nunc St.",
                            BusinessName = "At Associates",
                            ContactEmail = "ac@icloud.ca",
                            ContactPhone = "1-335-797-0988",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(486),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "25016570928"
                        },
                        new
                        {
                            ProviderId = new Guid("a80b8878-04b4-447a-be6c-b024c790c7cd"),
                            Address = "318-3230 Urna. Rd.",
                            BusinessName = "Nibh Donec Est Institute",
                            ContactEmail = "proin.non.massa@aol.org",
                            ContactPhone = "1-854-225-3383",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(491),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "24821225133"
                        },
                        new
                        {
                            ProviderId = new Guid("cf8ff22e-ae10-4956-bacf-dea02702e228"),
                            Address = "Ap #645-3636 Conubia Av.",
                            BusinessName = "Erat Volutpat Inc.",
                            ContactEmail = "elit.pretium@icloud.com",
                            ContactPhone = "(681) 652-3427",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(493),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "21546823173"
                        },
                        new
                        {
                            ProviderId = new Guid("9efb88a7-5e09-43eb-8502-60bb3f004edc"),
                            Address = "163-409 In, Rd.",
                            BusinessName = "Proin Eget Institute",
                            ContactEmail = "lobortis.mauris@google.net",
                            ContactPhone = "1-640-831-2711",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(496),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "24419741745"
                        },
                        new
                        {
                            ProviderId = new Guid("922ddff3-4c1d-4418-9173-8bcfe25dec1d"),
                            Address = "Ap #398-2179 Ligula Rd.",
                            BusinessName = "Laoreet Posuere Ltd",
                            ContactEmail = "quis@yahoo.org",
                            ContactPhone = "1-331-293-1812",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(498),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "20381813145"
                        },
                        new
                        {
                            ProviderId = new Guid("77e0147a-4d08-4d40-bd85-0fd15dd6eedf"),
                            Address = "573-5782 Ut Avenue",
                            BusinessName = "In Foundation",
                            ContactEmail = "fringilla.euismod.enim@outlook.couk",
                            ContactPhone = "(812) 908-3601",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(501),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "23374028741"
                        },
                        new
                        {
                            ProviderId = new Guid("78f3c3c6-67e2-4a74-8853-a6d84c0d49c8"),
                            Address = "P.O. Box 398, 5701 Enim Ave",
                            BusinessName = "Suspendisse Tristique Neque Foundation",
                            ContactEmail = "sed@aol.com",
                            ContactPhone = "(548) 947-6178",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(503),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "23886134764"
                        },
                        new
                        {
                            ProviderId = new Guid("1e307fb0-139f-4e7b-95f3-7ceeeda49dec"),
                            Address = "201 Auctor Rd.",
                            BusinessName = "Malesuada Associates",
                            ContactEmail = "ut.mi@icloud.com",
                            ContactPhone = "1-531-938-2251",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(507),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "28654072941"
                        },
                        new
                        {
                            ProviderId = new Guid("06566d2c-745c-486b-a790-491f20719c3f"),
                            Address = "733-4722 Mi. Avenue",
                            BusinessName = "Enim Sit Ltd",
                            ContactEmail = "ut.aliquam@icloud.com",
                            ContactPhone = "1-696-562-7023",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(509),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "28352851057"
                        },
                        new
                        {
                            ProviderId = new Guid("b8e60311-5d9a-4050-af72-e72064644b44"),
                            Address = "P.O. Box 604, 2268 Ac St.",
                            BusinessName = "Massa Limited",
                            ContactEmail = "at.libero.morbi@google.couk",
                            ContactPhone = "1-628-221-7892",
                            CreatedAt = new DateTime(2023, 10, 22, 17, 34, 3, 331, DateTimeKind.Local).AddTicks(514),
                            CreatedBy = new Guid("46dadb72-f4b7-400e-be4b-d58d36dc22dd"),
                            IsDeleted = false,
                            RUC = "22184652687"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
