// <auto-generated />
using System;
using InventoryX_Transactional.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryX_Transactional.Data.Migrations
{
    [DbContext(typeof(InventoryXDbContext))]
    [Migration("20231027022022_ChangeAuditEntityType")]
    partial class ChangeAuditEntityType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryX_Transactional.Data.Models.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6069));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsLegal")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ClientId");

                    b.ToTable("Client", (string)null);

                    b.HasData(
                        new
                        {
                            ClientId = new Guid("46aafcc4-038e-405f-bb60-2be721822c23"),
                            Address = "123 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1609),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "12345678",
                            DocumentType = 1,
                            Email = "alice@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Alice Chains",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            ClientId = new Guid("f2729523-5a6e-496b-bdb8-b5ff2988485f"),
                            Address = "456 Elm St, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1617),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "21345678901",
                            DocumentType = 2,
                            Email = "bob@yahoo.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Pepitos S.A.C",
                            Phone = "555-234-5678"
                        },
                        new
                        {
                            ClientId = new Guid("00d47cc9-1426-4844-bd3f-d065d7a3db62"),
                            Address = "789 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1624),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "87654321",
                            DocumentType = 1,
                            Email = "charlie@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Charlie Martinez",
                            Phone = "555-345-6789"
                        },
                        new
                        {
                            ClientId = new Guid("cda10968-e9eb-45ed-9f58-2cce7d8bc35a"),
                            Address = "567 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1627),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "007654321098765",
                            DocumentType = 3,
                            Email = "david@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "David Aguilar",
                            Phone = "555-456-7890"
                        },
                        new
                        {
                            ClientId = new Guid("c646f627-c241-44de-b2af-2c594c0ba1fd"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1629),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "13456789012",
                            DocumentType = 2,
                            Email = "eve@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Eve Medina",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("733d24d7-2b73-483b-8f9a-eed47b14ac91"),
                            Address = "321 Oak Dr, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1634),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "54321678",
                            DocumentType = 1,
                            Email = "frank@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Frank Jones",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("8c119865-cd6d-4c4b-b0ca-ee0b7721bfb9"),
                            Address = "789 Elm St, Chicago",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1653),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "002356789012345",
                            DocumentType = 3,
                            Email = "grace@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Grace",
                            Phone = "555-111-2222"
                        },
                        new
                        {
                            ClientId = new Guid("47fb6853-e129-4521-8107-accbb36e9453"),
                            Address = "456 Maple Ave, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1656),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "24567890123",
                            DocumentType = 2,
                            Email = "holly@yahoo.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Holly Store S.A.",
                            Phone = "555-444-5555"
                        },
                        new
                        {
                            ClientId = new Guid("13ed1949-ec50-4c35-8a04-76c5c8ffcee8"),
                            Address = "123 Cedar Ln, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1694),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "76543210",
                            DocumentType = 1,
                            Email = "ivy@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Ivy Williams",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("95e98d15-c2fd-4f2e-83e2-17c3a9c26cba"),
                            Address = "456 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1698),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "00345678601234",
                            DocumentType = 3,
                            Email = "jack@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Jack Smith",
                            Phone = "555-333-4444"
                        },
                        new
                        {
                            ClientId = new Guid("36da10c9-e82a-47dc-841a-58d266d5219e"),
                            Address = "123 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1701),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "87654321",
                            DocumentType = 1,
                            Email = "karen@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Karen Riques",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("ebbbbf6b-b08e-4710-be22-f978783bda27"),
                            Address = "456 Elm St, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1703),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "004567890123458",
                            DocumentType = 3,
                            Email = "liam@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Liam Nesson",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            ClientId = new Guid("af2ef9c0-145e-4d0c-a592-ff2d1cd695cd"),
                            Address = "789 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1705),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "22345228901",
                            DocumentType = 2,
                            Email = "mia@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Mia Shop",
                            Phone = "555-234-5678"
                        },
                        new
                        {
                            ClientId = new Guid("e02bab1e-eb4d-4b34-91c1-b1dcbffcdf28"),
                            Address = "567 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1708),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "98765432",
                            DocumentType = 1,
                            Email = "noah@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Noah Azora",
                            Phone = "555-345-6789"
                        },
                        new
                        {
                            ClientId = new Guid("504ac3d7-0806-4d65-9f47-74be525bb705"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1714),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "007654321098765",
                            DocumentType = 3,
                            Email = "olivia@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Olivia Fernandez",
                            Phone = "555-456-7890"
                        },
                        new
                        {
                            ClientId = new Guid("a3d30b39-5331-41d8-97c6-f8112480f993"),
                            Address = "123 Maple Ave, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1716),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "23456789012",
                            DocumentType = 2,
                            Email = "parker@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Parker Corp.",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("cc6ab48b-50ed-4325-ac65-b1e67d8b77bf"),
                            Address = "321 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1719),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "54321678",
                            DocumentType = 1,
                            Email = "quinn@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Client Eastwood",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("ef1acead-d566-4150-af5a-68ddf29bb2af"),
                            Address = "789 Elm St, Chicago",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1722),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "001236789012345",
                            DocumentType = 3,
                            Email = "ryan@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Ryan Dominguez",
                            Phone = "555-111-2222"
                        },
                        new
                        {
                            ClientId = new Guid("a1506e5e-6c34-4f99-b833-ae9b85ec8098"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1725),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "24567890697",
                            DocumentType = 2,
                            Email = "sofia@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Sofia Bazar",
                            Phone = "555-444-5555"
                        },
                        new
                        {
                            ClientId = new Guid("ed2a217d-0b7e-4bad-a745-c09271243e9c"),
                            Address = "123 Oak Dr, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(1727),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "76543210",
                            DocumentType = 1,
                            Email = "thomas@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Thomas Philipp",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("8a5b5d1d-c76c-4661-b48a-6220bd347f1e"),
                            Address = "123 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6431),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "12345678",
                            DocumentType = 1,
                            Email = "alice@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Alice Chains",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            ClientId = new Guid("92b4ac91-a334-4d12-ae15-d5961f45f4be"),
                            Address = "456 Elm St, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6438),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "21345678901",
                            DocumentType = 2,
                            Email = "bob@yahoo.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Pepitos S.A.C",
                            Phone = "555-234-5678"
                        },
                        new
                        {
                            ClientId = new Guid("5b6d02bd-e3dd-48d3-8281-2569509022ac"),
                            Address = "789 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6442),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "87654321",
                            DocumentType = 1,
                            Email = "charlie@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Charlie Martinez",
                            Phone = "555-345-6789"
                        },
                        new
                        {
                            ClientId = new Guid("21ed91aa-e3e3-45d6-b210-6d76808792aa"),
                            Address = "567 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6445),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "007654321098765",
                            DocumentType = 3,
                            Email = "david@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "David Aguilar",
                            Phone = "555-456-7890"
                        },
                        new
                        {
                            ClientId = new Guid("b93cb996-2983-4dd9-bcf1-48ab35bbcef6"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6449),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "13456789012",
                            DocumentType = 2,
                            Email = "eve@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Eve Medina",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("be66963c-6493-47dd-8d22-55ccf64ae151"),
                            Address = "321 Oak Dr, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6455),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "54321678",
                            DocumentType = 1,
                            Email = "frank@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Frank Jones",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("681eb5c3-8bab-4677-ad18-1793d3a1bad7"),
                            Address = "789 Elm St, Chicago",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6464),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "002356789012345",
                            DocumentType = 3,
                            Email = "grace@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Grace",
                            Phone = "555-111-2222"
                        },
                        new
                        {
                            ClientId = new Guid("5db45dfd-9ab5-4b9d-8d00-f603ea6eb1cd"),
                            Address = "456 Maple Ave, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6467),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "24567890123",
                            DocumentType = 2,
                            Email = "holly@yahoo.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Holly Store S.A.",
                            Phone = "555-444-5555"
                        },
                        new
                        {
                            ClientId = new Guid("5e15cf7b-bf22-416d-80cc-646f2bc15605"),
                            Address = "123 Cedar Ln, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6471),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "76543210",
                            DocumentType = 1,
                            Email = "ivy@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Ivy Williams",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("6bf4d83e-bdf4-485f-8788-ecd654fa4ead"),
                            Address = "456 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6475),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "00345678601234",
                            DocumentType = 3,
                            Email = "jack@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Jack Smith",
                            Phone = "555-333-4444"
                        },
                        new
                        {
                            ClientId = new Guid("bfde4b81-314f-4b4f-970b-e4ed656c4efc"),
                            Address = "123 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6478),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "87654321",
                            DocumentType = 1,
                            Email = "karen@gmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Karen Riques",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("456ee149-9ae2-4e23-940d-960e74ea4513"),
                            Address = "456 Elm St, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6482),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "004567890123458",
                            DocumentType = 3,
                            Email = "liam@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Liam Nesson",
                            Phone = "555-123-4567"
                        },
                        new
                        {
                            ClientId = new Guid("111eae65-debd-4a8a-895d-e5743e051c86"),
                            Address = "789 Oak Dr, Chicago",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6485),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "22345228901",
                            DocumentType = 2,
                            Email = "mia@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Mia Shop",
                            Phone = "555-234-5678"
                        },
                        new
                        {
                            ClientId = new Guid("ddcc1115-bc28-4cc7-a38a-2e63e288ea18"),
                            Address = "567 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6488),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "98765432",
                            DocumentType = 1,
                            Email = "noah@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Noah Azora",
                            Phone = "555-345-6789"
                        },
                        new
                        {
                            ClientId = new Guid("3f66c9f7-bfb2-407e-88d3-9ce87a7977a1"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6495),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "007654321098765",
                            DocumentType = 3,
                            Email = "olivia@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Olivia Fernandez",
                            Phone = "555-456-7890"
                        },
                        new
                        {
                            ClientId = new Guid("fcbb7986-ce60-4b80-a654-1dfc53a3c021"),
                            Address = "123 Maple Ave, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6498),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "23456789012",
                            DocumentType = 2,
                            Email = "parker@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Parker Corp.",
                            Phone = "555-567-8901"
                        },
                        new
                        {
                            ClientId = new Guid("59d657ef-db95-439a-8adb-f43f4513d33f"),
                            Address = "321 Cedar Ln, Houston",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6502),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "54321678",
                            DocumentType = 1,
                            Email = "quinn@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Client Eastwood",
                            Phone = "555-987-6543"
                        },
                        new
                        {
                            ClientId = new Guid("89ac1cc8-e732-43d8-9ed8-98c213410121"),
                            Address = "789 Elm St, Chicago",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6508),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "001236789012345",
                            DocumentType = 3,
                            Email = "ryan@hotmail.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Ryan Dominguez",
                            Phone = "555-111-2222"
                        },
                        new
                        {
                            ClientId = new Guid("1caf85e5-c758-4829-8c1f-2d9a878ee7c9"),
                            Address = "456 Main St, New York",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6511),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "24567890697",
                            DocumentType = 2,
                            Email = "sofia@gmail.com",
                            IsDeleted = false,
                            IsLegal = true,
                            Name = "Sofia Bazar",
                            Phone = "555-444-5555"
                        },
                        new
                        {
                            ClientId = new Guid("7472dcea-b3fe-424b-b93c-716935bb11a2"),
                            Address = "123 Oak Dr, Los Angeles",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(6514),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            DocumentNumber = "76543210",
                            DocumentType = 1,
                            Email = "thomas@yahoo.com",
                            IsDeleted = false,
                            IsLegal = false,
                            Name = "Thomas Philipp",
                            Phone = "555-987-6543"
                        });
                });

            modelBuilder.Entity("InventoryX_Transactional.Data.Models.Provider", b =>
                {
                    b.Property<Guid>("ProviderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValue(new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(7755));

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RUC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("ProviderId");

                    b.ToTable("Provider", (string)null);

                    b.HasData(
                        new
                        {
                            ProviderId = new Guid("50af111e-d4f7-4d0d-aa8c-f08b87a4dac1"),
                            Address = "P.O. Box 367, 4325 Augue Rd.",
                            BusinessName = "Augue Corporation",
                            ContactEmail = "in.tempus@google.com",
                            ContactPhone = "(498) 810-4710",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(3948),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "28851161316"
                        },
                        new
                        {
                            ProviderId = new Guid("1af9bc2a-8003-420a-b65a-4621c63ba182"),
                            Address = "716-9139 Lectus, Road",
                            BusinessName = "Feugiat Nec Foundation",
                            ContactEmail = "ut.tincidunt@yahoo.net",
                            ContactPhone = "1-324-172-5394",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(3958),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "21425812564"
                        },
                        new
                        {
                            ProviderId = new Guid("e69baec9-8f8d-41e4-8f84-faeb7e7ee568"),
                            Address = "P.O. Box 994, 6300 Id Rd.",
                            BusinessName = "Dis Parturient Montes Associates",
                            ContactEmail = "donec.luctus@aol.edu",
                            ContactPhone = "1-948-625-3851",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(3973),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "20907865658"
                        },
                        new
                        {
                            ProviderId = new Guid("ba68bf1e-743e-4f8b-a36b-2a1251ff7679"),
                            Address = "Ap #121-5878 Nulla. St.",
                            BusinessName = "Egestas Rhoncus Corp.",
                            ContactEmail = "pede@icloud.net",
                            ContactPhone = "(487) 387-0723",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(3978),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "21438271486"
                        },
                        new
                        {
                            ProviderId = new Guid("16684e88-5050-468d-a76d-6cf21f99278c"),
                            Address = "523-8707 Et Rd.",
                            BusinessName = "Nullam Nisl Maecenas PC",
                            ContactEmail = "vulputate@protonmail.couk",
                            ContactPhone = "(685) 481-5523",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(3981),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "23414517112"
                        },
                        new
                        {
                            ProviderId = new Guid("82f17875-55d7-4e22-9243-aa347a9d23e0"),
                            Address = "938-7069 Lobortis, Av.",
                            BusinessName = "Turpis Egestas Fusce Inc.",
                            ContactEmail = "donec.feugiat.metus@google.ca",
                            ContactPhone = "(744) 465-4414",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(3988),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "20534218461"
                        },
                        new
                        {
                            ProviderId = new Guid("4be1fc2a-3e01-467c-a7f4-5dbea851c2dd"),
                            Address = "Ap #717-2261 Mi Avenue",
                            BusinessName = "Sem Limited",
                            ContactEmail = "lacinia@yahoo.ca",
                            ContactPhone = "(512) 376-4277",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(3992),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "27145868620"
                        },
                        new
                        {
                            ProviderId = new Guid("dc451d55-41f0-4d78-9fac-0e1e8defc451"),
                            Address = "P.O. Box 145, 8931 Vitae Rd.",
                            BusinessName = "Elit A Feugiat Corp.",
                            ContactEmail = "consectetuer.ipsum.nunc@hotmail.net",
                            ContactPhone = "(445) 745-2317",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(3995),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "28163725354"
                        },
                        new
                        {
                            ProviderId = new Guid("fcb44a71-0a69-47e8-96eb-06c97fe01ada"),
                            Address = "Ap #312-3859 Arcu. Street",
                            BusinessName = "Vitae Velit LLC",
                            ContactEmail = "at@icloud.ca",
                            ContactPhone = "1-202-357-4151",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(3999),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "20177426605"
                        },
                        new
                        {
                            ProviderId = new Guid("f91115d4-99f6-4d11-a1af-2f15362b2463"),
                            Address = "430-6187 Malesuada Ave",
                            BusinessName = "Lorem Ipsum Institute",
                            ContactEmail = "orci.donec.nibh@aol.ca",
                            ContactPhone = "(747) 407-6648",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4005),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "24334730132"
                        },
                        new
                        {
                            ProviderId = new Guid("b248bd17-5f7c-47c3-85c9-79edddab8c5b"),
                            Address = "2259 Nunc St.",
                            BusinessName = "At Associates",
                            ContactEmail = "ac@icloud.ca",
                            ContactPhone = "1-335-797-0988",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4013),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "25016570928"
                        },
                        new
                        {
                            ProviderId = new Guid("c6f70704-0614-4f8a-a140-0368d12aa515"),
                            Address = "318-3230 Urna. Rd.",
                            BusinessName = "Nibh Donec Est Institute",
                            ContactEmail = "proin.non.massa@aol.org",
                            ContactPhone = "1-854-225-3383",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4017),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "24821225133"
                        },
                        new
                        {
                            ProviderId = new Guid("e6c23a9e-853e-428a-baff-6e280e0e1d3e"),
                            Address = "Ap #645-3636 Conubia Av.",
                            BusinessName = "Erat Volutpat Inc.",
                            ContactEmail = "elit.pretium@icloud.com",
                            ContactPhone = "(681) 652-3427",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4063),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "21546823173"
                        },
                        new
                        {
                            ProviderId = new Guid("2990e7e3-a45e-453d-aba7-3af66f1fcf90"),
                            Address = "163-409 In, Rd.",
                            BusinessName = "Proin Eget Institute",
                            ContactEmail = "lobortis.mauris@google.net",
                            ContactPhone = "1-640-831-2711",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4068),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "24419741745"
                        },
                        new
                        {
                            ProviderId = new Guid("989a6dbd-f178-481a-8ee1-a34cfd831a5a"),
                            Address = "Ap #398-2179 Ligula Rd.",
                            BusinessName = "Laoreet Posuere Ltd",
                            ContactEmail = "quis@yahoo.org",
                            ContactPhone = "1-331-293-1812",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4072),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "20381813145"
                        },
                        new
                        {
                            ProviderId = new Guid("7dd722d1-7799-4cca-927c-69e3d7e6eaf3"),
                            Address = "573-5782 Ut Avenue",
                            BusinessName = "In Foundation",
                            ContactEmail = "fringilla.euismod.enim@outlook.couk",
                            ContactPhone = "(812) 908-3601",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4075),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "23374028741"
                        },
                        new
                        {
                            ProviderId = new Guid("a8b982ab-a950-4834-9931-fc5aa55e0be7"),
                            Address = "P.O. Box 398, 5701 Enim Ave",
                            BusinessName = "Suspendisse Tristique Neque Foundation",
                            ContactEmail = "sed@aol.com",
                            ContactPhone = "(548) 947-6178",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4079),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "23886134764"
                        },
                        new
                        {
                            ProviderId = new Guid("ce093169-745c-44f7-98da-ac1496bcbd67"),
                            Address = "201 Auctor Rd.",
                            BusinessName = "Malesuada Associates",
                            ContactEmail = "ut.mi@icloud.com",
                            ContactPhone = "1-531-938-2251",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4084),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "28654072941"
                        },
                        new
                        {
                            ProviderId = new Guid("c46805ce-58bf-4622-ac23-90cb4add1971"),
                            Address = "733-4722 Mi. Avenue",
                            BusinessName = "Enim Sit Ltd",
                            ContactEmail = "ut.aliquam@icloud.com",
                            ContactPhone = "1-696-562-7023",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4092),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "28352851057"
                        },
                        new
                        {
                            ProviderId = new Guid("eaa9e653-6216-4a96-8899-267328012d81"),
                            Address = "P.O. Box 604, 2268 Ac St.",
                            BusinessName = "Massa Limited",
                            ContactEmail = "at.libero.morbi@google.couk",
                            ContactPhone = "1-628-221-7892",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(4096),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "22184652687"
                        },
                        new
                        {
                            ProviderId = new Guid("7b6f247f-c926-44b7-b363-a35242d94f11"),
                            Address = "P.O. Box 367, 4325 Augue Rd.",
                            BusinessName = "Augue Corporation",
                            ContactEmail = "in.tempus@google.com",
                            ContactPhone = "(498) 810-4710",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8089),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "28851161316"
                        },
                        new
                        {
                            ProviderId = new Guid("ec19d417-5a93-4db8-87ec-a50c231e8d7a"),
                            Address = "716-9139 Lectus, Road",
                            BusinessName = "Feugiat Nec Foundation",
                            ContactEmail = "ut.tincidunt@yahoo.net",
                            ContactPhone = "1-324-172-5394",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8097),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "21425812564"
                        },
                        new
                        {
                            ProviderId = new Guid("17621ff2-a421-43c2-8414-fe84c108132a"),
                            Address = "P.O. Box 994, 6300 Id Rd.",
                            BusinessName = "Dis Parturient Montes Associates",
                            ContactEmail = "donec.luctus@aol.edu",
                            ContactPhone = "1-948-625-3851",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8106),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "20907865658"
                        },
                        new
                        {
                            ProviderId = new Guid("ca4ad85c-3803-4050-b497-1f03b7a3acb0"),
                            Address = "Ap #121-5878 Nulla. St.",
                            BusinessName = "Egestas Rhoncus Corp.",
                            ContactEmail = "pede@icloud.net",
                            ContactPhone = "(487) 387-0723",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8110),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "21438271486"
                        },
                        new
                        {
                            ProviderId = new Guid("233f89e3-b78c-4daa-8a24-34770e8ba9ce"),
                            Address = "523-8707 Et Rd.",
                            BusinessName = "Nullam Nisl Maecenas PC",
                            ContactEmail = "vulputate@protonmail.couk",
                            ContactPhone = "(685) 481-5523",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8114),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "23414517112"
                        },
                        new
                        {
                            ProviderId = new Guid("571cdf8f-fbc0-4ae6-855c-75744eb5494f"),
                            Address = "938-7069 Lobortis, Av.",
                            BusinessName = "Turpis Egestas Fusce Inc.",
                            ContactEmail = "donec.feugiat.metus@google.ca",
                            ContactPhone = "(744) 465-4414",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8121),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "20534218461"
                        },
                        new
                        {
                            ProviderId = new Guid("d46ca5e4-4478-47a0-87ae-e0a656cc2fd0"),
                            Address = "Ap #717-2261 Mi Avenue",
                            BusinessName = "Sem Limited",
                            ContactEmail = "lacinia@yahoo.ca",
                            ContactPhone = "(512) 376-4277",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8125),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "27145868620"
                        },
                        new
                        {
                            ProviderId = new Guid("8e073af7-dd73-4615-9ad4-5756d2ae716b"),
                            Address = "P.O. Box 145, 8931 Vitae Rd.",
                            BusinessName = "Elit A Feugiat Corp.",
                            ContactEmail = "consectetuer.ipsum.nunc@hotmail.net",
                            ContactPhone = "(445) 745-2317",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8129),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "28163725354"
                        },
                        new
                        {
                            ProviderId = new Guid("5b24397b-ad44-421e-aa1d-ce2ef64ce078"),
                            Address = "Ap #312-3859 Arcu. Street",
                            BusinessName = "Vitae Velit LLC",
                            ContactEmail = "at@icloud.ca",
                            ContactPhone = "1-202-357-4151",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8133),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "20177426605"
                        },
                        new
                        {
                            ProviderId = new Guid("7d27de99-5c82-49de-8e11-85633eb99d11"),
                            Address = "430-6187 Malesuada Ave",
                            BusinessName = "Lorem Ipsum Institute",
                            ContactEmail = "orci.donec.nibh@aol.ca",
                            ContactPhone = "(747) 407-6648",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8138),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "24334730132"
                        },
                        new
                        {
                            ProviderId = new Guid("69a1758e-5382-4b3f-a9bb-acf111902edd"),
                            Address = "2259 Nunc St.",
                            BusinessName = "At Associates",
                            ContactEmail = "ac@icloud.ca",
                            ContactPhone = "1-335-797-0988",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8147),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "25016570928"
                        },
                        new
                        {
                            ProviderId = new Guid("950a9814-3b31-46e8-b5b9-cd268deeded7"),
                            Address = "318-3230 Urna. Rd.",
                            BusinessName = "Nibh Donec Est Institute",
                            ContactEmail = "proin.non.massa@aol.org",
                            ContactPhone = "1-854-225-3383",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8151),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "24821225133"
                        },
                        new
                        {
                            ProviderId = new Guid("50835725-5f20-4244-882f-99ef0741f29d"),
                            Address = "Ap #645-3636 Conubia Av.",
                            BusinessName = "Erat Volutpat Inc.",
                            ContactEmail = "elit.pretium@icloud.com",
                            ContactPhone = "(681) 652-3427",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8156),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "21546823173"
                        },
                        new
                        {
                            ProviderId = new Guid("0d8ebe43-b63d-42d3-b061-a1865984c973"),
                            Address = "163-409 In, Rd.",
                            BusinessName = "Proin Eget Institute",
                            ContactEmail = "lobortis.mauris@google.net",
                            ContactPhone = "1-640-831-2711",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8161),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "24419741745"
                        },
                        new
                        {
                            ProviderId = new Guid("9cfa5f90-466d-457d-8ab3-6b33b4a4860b"),
                            Address = "Ap #398-2179 Ligula Rd.",
                            BusinessName = "Laoreet Posuere Ltd",
                            ContactEmail = "quis@yahoo.org",
                            ContactPhone = "1-331-293-1812",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8165),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "20381813145"
                        },
                        new
                        {
                            ProviderId = new Guid("58b6afa0-b586-4595-a87f-77727aa313de"),
                            Address = "573-5782 Ut Avenue",
                            BusinessName = "In Foundation",
                            ContactEmail = "fringilla.euismod.enim@outlook.couk",
                            ContactPhone = "(812) 908-3601",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8168),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "23374028741"
                        },
                        new
                        {
                            ProviderId = new Guid("cd3d0632-892a-47d1-9f25-c6cbd4940939"),
                            Address = "P.O. Box 398, 5701 Enim Ave",
                            BusinessName = "Suspendisse Tristique Neque Foundation",
                            ContactEmail = "sed@aol.com",
                            ContactPhone = "(548) 947-6178",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8173),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "23886134764"
                        },
                        new
                        {
                            ProviderId = new Guid("50147341-c9a0-4253-b358-b9f908479a23"),
                            Address = "201 Auctor Rd.",
                            BusinessName = "Malesuada Associates",
                            ContactEmail = "ut.mi@icloud.com",
                            ContactPhone = "1-531-938-2251",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8179),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "28654072941"
                        },
                        new
                        {
                            ProviderId = new Guid("0444271b-d94a-4317-9688-903ece98a496"),
                            Address = "733-4722 Mi. Avenue",
                            BusinessName = "Enim Sit Ltd",
                            ContactEmail = "ut.aliquam@icloud.com",
                            ContactPhone = "1-696-562-7023",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8189),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "28352851057"
                        },
                        new
                        {
                            ProviderId = new Guid("83b105ca-ae8b-4d3c-a571-b4282d837427"),
                            Address = "P.O. Box 604, 2268 Ac St.",
                            BusinessName = "Massa Limited",
                            ContactEmail = "at.libero.morbi@google.couk",
                            ContactPhone = "1-628-221-7892",
                            CreatedAt = new DateTime(2023, 10, 26, 21, 20, 22, 71, DateTimeKind.Local).AddTicks(8193),
                            CreatedBy = "46dadb72-f4b7-400e-be4b-d58d36dc22dd",
                            IsDeleted = false,
                            RUC = "22184652687"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
